CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/banana_rgba.png --text "a half-peeled yellow banana" --workspace trial_imagetext_rf_banana_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5 
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/banana_rgba.png --text "a half-peeled yellow banana" --workspace trial2_imagetext_rf_banana_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_banana_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_banana_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/bird_rgba.png --text "a small blue-brown bird with a pointed mouth" --workspace trial_imagetext_rf_bird_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/bird_rgba.png --text "a small blue-brown bird with a pointed mouth" --workspace trial2_imagetext_rf_bird_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_bird_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_bird_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/cactus_rgba.png --text "a green cactus in a brown pot" --workspace trial_imagetext_rf_cactus_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/cactus_rgba.png --text "a green cactus in a brown pot" --workspace trial2_imagetext_rf_cactus_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_cactus_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_cactus_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/cake_rgba.png --text "a Barbie doll in a pink dress" --workspace trial_imagetext_rf_cake_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/cake_rgba.png --text "a Barbie doll in a pink dress" --workspace trial2_imagetext_rf_cake_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_cake_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_cake_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/cat_statue_rgba.png --text "a cat statue in colorful suit" --workspace trial_imagetext_rf_cat_statue_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/cat_statue_rgba.png --text "a cat statue in colorful suit" --workspace trial2_imagetext_rf_cat_statue_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_cat_statue_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_cat_statue_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/cheery_rgba.png --text "a red cheery" --workspace trial_imagetext_rf_cheery_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/cheery_rgba.png --text "a red cheery" --workspace trial2_imagetext_rf_cheery_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_cheery_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_cheery_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/colorful_teapot_rgba.png --text "a colorful teapot" --workspace trial_imagetext_rf_colorful_teapot_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/colorful_teapot_rgba.png --text "a colorful teapot" --workspace trial2_imagetext_rf_colorful_teapot_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_colorful_teapot_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_colorful_teapot_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/donut_rgba.png --text "two pink doughnuts next to each other" --workspace trial_imagetext_rf_donut_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/donut_rgba.png --text "two pink doughnuts next to each other" --workspace trial2_imagetext_rf_donut_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_donut_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_donut_clip/convergence.npy
 
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/dragon_statue1_rgba.png --text "a silver dragon statue with long horns and large wings" --workspace trial_imagetext_rf_dragon_statue1_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/dragon_statue1_rgba.png --text "a silver dragon statue with long horns and large wings" --workspace trial2_imagetext_rf_dragon_statue1_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_dragon_statue1_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_dragon_statue1_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/dragon_statue2_rgba.png --text "a silver dragon statue with short horns and small wings" --workspace trial_imagetext_rf_dragon_statue2_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/dragon_statue2_rgba.png --text "a silver dragon statue with short horns and small wings" --workspace trial2_imagetext_rf_dragon_statue2_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_dragon_statue2_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_dragon_statue2_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/fish_real_nemo_rgba.png --text "a clownfish" --workspace trial_imagetext_rf_fish_real_nemo_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/fish_real_nemo_rgba.png --text "a clownfish" --workspace trial2_imagetext_rf_fish_real_nemo_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_fish_real_nemo_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_fish_real_nemo_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/horse_watercolor_2_rgba.png --text "a watercolor of a brown horse" --workspace trial_imagetext_rf_horse_watercolor_2_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/horse_watercolor_2_rgba.png --text "a watercolor of a brown horse" --workspace trial2_imagetext_rf_horse_watercolor_2_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_horse_watercolor_2_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_horse_watercolor_2_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/microphone_rgba.png --text "a black microphone" --workspace trial_imagetext_rf_microphone_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/microphone_rgba.png --text "a black microphone" --workspace trial2_imagetext_rf_microphone_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_microphone_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_microphone_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/sparrow_rgba.png --text "a grey sparrow" --workspace trial_imagetext_rf_sparrow_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/sparrow_rgba.png --text "a grey sparrow" --workspace trial2_imagetext_rf_sparrow_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_sparrow_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_sparrow_clip/convergence.npy

CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/teddy_bear_rgba.png --text "a brown teddy_bear bear sitting on a ground" --workspace trial_imagetext_rf_teddy_bear_clip  --iters 5000 --dmtet_iters 5000 --least_3Donly 2000 --most_3Donly 3500 --render_interval 21 --threshold 0.00025 --last_N 5
CUDA_VISIBLE_DEVICES=2 python main.py --weight_method exponential -O --image data/realfusion15/teddy_bear_rgba.png --text "a brown teddy_bear bear sitting on a ground" --workspace trial2_imagetext_rf_teddy_bear_clip --iters 5000 --dmtet --init_with trial_imagetext_rf_teddy_bear_clip/checkpoints/df.pth --nerf_iters 5000 --convergence_path trial_imagetext_rf_teddy_bear_clip/convergence.npy